<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mg</string>
	</array>
	<key>name</key>
	<string>Mudguard</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#var_name</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#label</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#typedecl</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#regexp</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#property</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#type</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_simple</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>comment</key>
			<string>Comment</string>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.line.number-sign.mg</string>
		</dict>
		<key>constant</key>
		<dict>
			<key>match</key>
			<string>\b(undefined|true|false|now|tomorrow|yesterday)\b</string>
			<key>name</key>
			<string>constant.language.mg</string>
		</dict>
		<key>escape</key>
		<dict>
			<key>match</key>
			<string>\\.</string>
			<key>name</key>
			<string>constant.character.escape.mg</string>
		</dict>
		<key>keyword</key>
		<dict>
			<key>match</key>
			<string>\b(set|and|or|as|if|not|else|elif|endif|in|is|default)\b</string>
			<key>name</key>
			<string>keyword.other.mg</string>
		</dict>
		<key>label</key>
		<dict>
			<key>match</key>
			<string>\w+\s*:</string>
			<key>name</key>
			<string>entity.name.mg</string>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>(0x|0o)?[0-9]+(\.[0-9]+)?</string>
			<key>name</key>
			<string>constant.numeric.mg</string>
		</dict>
		<key>operator</key>
		<dict>
			<key>match</key>
			<string>(\{|\}|\||\(|\))</string>
			<key>name</key>
			<string>keyword.operator.mg</string>
		</dict>
		<key>property</key>
		<dict>
			<key>match</key>
			<string>![a-zA-Z_][a-zA-Z0-9_]*</string>
			<key>name</key>
			<string>support.function.mg</string>
		</dict>
		<key>regexp</key>
		<dict>
			<key>begin</key>
			<string>/</string>
			<key>end</key>
			<string>/:?</string>
			<key>name</key>
			<string>string.regexp.mg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.regexp</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>(["'])</string>
			<key>end</key>
			<string>\1</string>
			<key>name</key>
			<string>string.quoted.mg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
			</array>
		</dict>
		<key>string_simple</key>
		<dict>
			<key>match</key>
			<string>[a-zA-Z_][a-zA-Z0-9_]*</string>
			<key>name</key>
			<string>string.other.mg</string>
		</dict>
		<key>type</key>
		<dict>
			<key>match</key>
			<string>(\b(number|string|date|boolean|integer)\b|\*[a-zA-Z_][a-zA-Z0-9_]*)</string>
			<key>name</key>
			<string>storage.type.mg</string>
		</dict>
		<key>typedecl</key>
		<dict>
			<key>match</key>
			<string>&amp;[a-zA-Z_][a-zA-Z0-9_]*</string>
			<key>name</key>
			<string>support.type.mg</string>
		</dict>
		<key>var_name</key>
		<dict>
			<key>match</key>
			<string>\$[a-zA-Z_][a-zA-Z0-9_]*</string>
			<key>name</key>
			<string>variable.other.mg</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.mg</string>
	<key>uuid</key>
	<string>3814d5f3-a8c7-4590-89cc-b9e343b7aef6</string>
</dict>
</plist>
